### ISSUE TITLE
PDF creator fails

### ISSUE THREAD

**Issue by moniquewiza** [EUSurvey/EUSURVEY#266]
During pdf creation the system crashes

2020-08-04 17:32:31-93669874 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-1831] (PDFService.java:148) INFO  com.ec.survey.service.BasicService  - starting creation of answer pdf for contribution 749db2d7-9f94-4053-9f92-5fd853581c21 to be sent to null
2020-08-04 17:32:31-93669890 [taskExecutor-10] (PDFService.java:240) INFO  com.ec.survey.service.BasicService  - 12100
2020-08-04 17:32:31-93669890 [taskExecutor-10] (PDFService.java:248) INFO  com.ec.survey.service.BasicService  - starting PDF creation target is C:\eusurveyfs\surveys\9\9aaa8179-22d2-4c02-9f2c-b7ba89744ea8\EXPORTS\answer749db2d7-9f94-4053-9f92-5fd853581c21.pdf
2020-08-04 17:32:31-93669936 [taskExecutor-10] (PDFRenderer.java:137) ERROR com.ec.survey.tools.PDFRenderer  - PDFRender.createPDF Error org.xml.sax.SAXParseException; systemId: http://surveys.sitename.com/eusurvey/preparecontribution/749db2d7-9f94-4053-9f92-5fd853581c21; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.
2020-08-04 17:32:31-93669936 [taskExecutor-10] (PDFService.java:263) ERROR com.ec.survey.service.BasicService  - PDF creation for answer 749db2d7-9f94-4053-9f92-5fd853581c21 could not be started.
2020-08-04 17:32:31-93669936 [taskExecutor-10] (PDFService.java:264) ERROR com.ec.survey.service.BasicService  - White spaces are required between publicId and systemId.
org.xml.sax.SAXParseException; systemId: http://surveys.sitename.com/eusurvey/preparecontribution/749db2d7-9f94-4053-9f92-5fd853581c21; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at com.ec.survey.tools.PDFRenderer.createPDF(PDFRenderer.java:126)
	at com.ec.survey.service.PDFService.createAnswerPDF(PDFService.java:258)
	at com.ec.survey.tools.AnswerExecutor.run(AnswerExecutor.java:83)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by moniquewiza** [comment]
@clam2310 , @catalry
Hi, this is a critical issue, cause users cannot print also their submissions. In general PDF creation fails all the time.
Please comment

**Comment by catalry** [comment]
Hello @wojciechwiza , can you tell us more about your issue? Which version of EUSURVEY are you using?

**Comment by moniquewiza** [comment]
Hi @catalry 

we are using v1.5 c543b30df31715f8b4a9691054a155b61e8c8422 (07/08/2020 10:43)

**Comment by wojciechwiza** [comment]
Hi @catalry any news on that? Can I help with something?

**Comment by moniquewiza** [comment]
Hi @catalry 
I've solved the issue. The problem was related to spring.properites file where all urls (by default) are with HTTP while our server runs with HTTPS. When changed all URLs to https the PDF works ok.

Maybe it would be good to change all http to https in default spring.properites?
